title: My first github page 
author: Dennis van den Berg
email: dennisvandenberg13100@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This Blog is just a test to understand how the github-pages works
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  dennisberg13100 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
